### ISSUE TITLE
Dynamic Sortable options

### ISSUE THREAD

**Issue by palagadec** [MaxLeiter/sortablejs-vue3#16]
Hello,
I'm trying to enable/disable sorting by using the component prop `:options="dragOptions"` with a computed object like so :
```
const dragOptions = computed(() => ({
	animation: 200,
	ghostClass: "ghost",
	disabled: !isSorting.value,
}));
```

However, dynamically changing the `disabled` property doesn't toggle sorting.
I found a way to "force" the update by changing the wrapping tag like so : `:tag="isSorting ? 'div' : 'section'"` but it's not a really clean solution.

**Comment by MaxLeiter** [comment]
Thanks for the report @palagadec

I pushed a potential fix -- can you try it? I didn't make a release so you'll need to test from git. I updated the home page to act as a quick example, you can now toggle the animations. Let me know if you have any questions.

**Comment by palagadec** [comment]
Thanks for the quick update !
Tried it, works perfectly ! 😁

**Comment by MaxLeiter** [comment]
@palagadec version 1.2.0 has been released
