### ISSUE TITLE
There is no lib files in the package downloaded with yarn

### ISSUE THREAD

**Issue by billyct** [MaxLeiter/sortablejs-vue3#2]
seems there is no `./dist/sortablejs-vue3.umd.js` and `./dist/sortablejs-vue3.es.js` files 

in the `node_module/dist` folder

<img width="200" alt="image" src="https://user-images.githubusercontent.com/1612364/173980401-ec8b35c3-6a64-4053-9ecf-a9d5c0ef88b8.png">

**Comment by MaxLeiter** [comment]
The merged workflow action isn't working with 2FA, so I need to fix that up.

**Comment by MaxLeiter** [comment]
Seems to be fixed in v1.0.3. https://www.runpkg.com/?sortablejs-vue3@1.0.1/dist/sortablejs-vue3.umd.js
