### ISSUE TITLE
Managing state when moving items between lists

### ISSUE THREAD

**Issue by nlhkabu** [MaxLeiter/sortablejs-vue3#23]
Thanks again for this lib.

I have several lists on my page, and want to be able to drag items between lists. For this, I give every list the same sortable `group` option.

This is how I am trying to manage the state when dragging an item between lists:

1. use `remove` event to remove item from the state
2. use `add` event to add the item back to the state in its new location

My state is updating just fine, however, the orginal DOM element is moved to the new list (and *not* removed from the DOM). This results in duplicates (because my state also creates a new element).

Currently, it looks like my options are to either:
1. manually remove the DOM element with `event.item.remove()` OR
2. force re-render my component to keep the state in sync

Both of these seem hacky - is there a better approach?

**Comment by nlhkabu** [comment]
For context, here is the problem in action:
https://github.com/nlhkabu/sortablejs-vue3/tree/add-store

**Comment by MaxLeiter** [comment]
Thanks for the detailed issue + repro! I'll try and investigate tonight or tomorrow and will respond back here

**Comment by Chuuone** [comment]
If you compare the approach of another library they also seem to remove the item onDragAdd manually, allowing for the component to render its own with v-for. I dont think sortableJS provides any options for renderless listing.

https://github.com/SortableJS/Vue.Draggable/blob/017ab498428efef966d72ea2be547cb0213cd6bb/src/vuedraggable.js#L406

**Comment by MaxLeiter** [comment]
Thanks for the info, @Chuuone. I got a little caught up with work and wasn't able to work on this, but that's very helpful.

**Comment by nlhkabu** [comment]
Thank you @Chuuone - that's what we decided to do in the end :)

**Comment by goldyfruit** [comment]
I'm facing the same behavior, with `vue.draggable.next` I can move an item from a list to an other. I don't really know how to workaround this.

```
<draggable :component-data="{name:'fade', type: 'transtion-group'}" v-model="modules" group="modules"
            item-key="module" class="q-pa-md row items-start q-gutter-md" :move="test" @start="dragging = true"
            @end="dragging = false" v-bind="dragOptions">
```

```
<Sortable :list="modules" item-key="module" :options="options" class="q-pa-md row items-start q-gutter-md">
```

**Comment by MaxLeiter** [comment]
@goldyfruit are your `group`s the same? Or am I misunderstanding what you want to do?

**Comment by jakubserwin** [comment]
I am also having the same issue. In my case, when I move an item between lists I am removing and adding it in the database, which then reflects the state of the lists. As above my state reflect it correctly, hoverer Sortable duplicates the item in list. 

Firstly it creates some ghost item with draggable="false" and then my proper item is added which makes two same items at the end.

**Comment by nlhkabu** [comment]
@MaxLeiter - I wonder if supporting this fork of sortable would enable folks to manage state better?
https://github.com/SortableJS/Sortable/pull/2195

I have been looking into this as I am experiencing another issue where the DOM and state get out of sync (when adding an item to the list after drag and drop it is added in the wrong place).

I tried to create a fork of your library but got stuck.  I would be happy to work through this with you if you think it is a viable option for the lib.

**Comment by Gahotx** [comment]
I have the same problem. When I use the [method](https://github.com/MaxLeiter/sortablejs-vue3#use-with-a-store) to manage the data in pinia, it will affect the sorting of DOM. It is a similar problem to this issue https://github.com/vueuse/vueuse/issues/2924

**Comment by kburton-dev** [comment]
Anyone got a solution to this yet?

**Comment by MaxLeiter** [comment]
Sorry @nlhkabu, I completely missed your offer. It's probably too late to be of help for you, but that fork seems like a great solution with the caveat of multidrag not working. I intend to look into it soon

**Comment by garbit** [comment]
I'm experiencing the same issue where I have two separate `Sortable` lists that I want to move items between using a shared group name. I load the state of the sortable lists from a pinia store and I detect that items have been moved using the `@end` event.

When I move an item between the two lists the item is removed from the previous parent but is then duplicated in the new parent list. 

I managed to get around this by listening to the `@end` event, performing my pinia update, and then calling `event.item.remove()` which removes the shadow element in the new parent group.

```javascript
async function moveItem(event: { newIndex: number | undefined, oldIndex: number | undefined, item: HTMLElement, to: HTMLElement, parentId: string }) {
  const op = {
    type: EditorOperationType.MOVE,
    fromIndex: event.oldIndex,
    toIndex: event.newIndex,
    fromParentId: parentItem.item.itemId,
    toParentId: destinationParentItem.item.itemId,
    item: draftItem.item,
    itemId: draftItem.item.itemId,
  } as MoveOperation
  myStore.addOperation(op)
  event.item.remove() <- here
}

<template>
   <Sortable
    :list="myStore.state.list"
    item-key="id"
    :options="{
      handle: '.grab-handle',
      group: {
        name: 'items',
      },
    }"
    class="flex flex-col gap-2"
    :data-id="itemId"
    @end="(event) => moveItem(event)"
  >
    <template #item="{ element: item }">
      <div :id="item.id class="flex items-center" :data-id="item.id>
        <div :key="item.id" class="draggable grab-handle">
          <div>
            <Icon name="mdi:drag" class="cursor-move size-5 text-gray-500" />
          </div>
        </div>
        <div class="flex-1">
             {{ item.id }}
        </div>
      </div>
    </template>
  </Sortable>
</template>
```

**Comment by garbit** [comment]
Further update to this - when using `uuidv4()` as the key the list is forced to re-render however this is causing any input fields within the nested list to lose focus when any field in the list is clicked on.
