### ISSUE TITLE
npm  script 

### ISSUE THREAD

**Issue by hxzAugustinus** [MaxLeiter/sortablejs-vue3#29]
![image](https://user-images.githubusercontent.com/14306029/191935113-8c0d946b-4c1c-4f0e-af41-7e7d9d01aa5b.png)

question:
 i  dont   understand  the  command , beacuse i  delete ,it also can compile ok ,  anyone  can explain ?

**Comment by MaxLeiter** [comment]
This is for building the demo website and not the library itself
