### ISSUE TITLE
Nested draggable children

### ISSUE THREAD

**Issue by lucianobosco** [MaxLeiter/sortablejs-vue3#32]
Despite I've tried I'm not able to make it work with nested children. I've added `:group` prop but no luck so far.
So my question is: is this library able to handle nested children and can we swap children between parents?

**Comment by MaxLeiter** [comment]
Yes, that should be supported. You can see an example here: https://github.com/thelounge/thelounge/blob/master/client/components/NetworkList.vue#L56

If you provide an example or some code I can offer more help

**Comment by MaxLeiter** [comment]
Closing without any further information.

**Comment by syuilo** [comment]
I need support for this feature.
