### ISSUE TITLE
Manage state when moving items between two lists

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [MaxLeiter/sortablejs-vue3#40]
Thanks again for this lib.

I have multiple lists on my page and I want to be able to change some properties of my project. As with [vue.draggable.next clone,](https://sortablejs.github.io/vue.draggable.next/#/clone) I have provided the same grouping options for each list.

Now the question is:

1. The 'taskList' has not been updated. The page already has the project, and the properties haven't changed

The sample code:
```
<template>
         <Sortable class="draggable" :list="elements" item-key="id" tag="div" :options="options" @clone="onClone">
            <template #item="{ element, index }">
                <div class="draggable" :key="element.id">
                    {{ element.name }}
                </div>
            </template>
        </Sortable>

         <Sortable class="draggable" :list="taskList" item-key="id" tag="div" :options="options">
            <template #item="{ element, index }">
                <div class="draggable" :key="element.id">
                    {{ element.name }}
                </div>
            </template>
        </Sortable>

</template>

<script setup>
const options = ref({
    group: "name",
})
const elements = ref([{ id: uuidv4(), name: "test1" }])
const taskList = ref([])
const onClone = function (evt) {
    let { oldIndex, } = evt;

    const obj = elements[oldIndex];
    let tempObj = {
        ...obj,
        id: uuidv4()
    }
    taskList.value.push(tempObj)
}

</script>

```

**Comment by MaxLeiter** [comment]
Please see https://stackblitz.com/edit/recursive-template-refs-b2umvk?file=src/components/EntryListItem.vue this example for how to handle managing state manually. In 2.0 this could become something the library handles for you -- contributions welcome!
