### ISSUE TITLE
Not working properly on latest Chrome

### ISSUE THREAD

**Issue by singerla** [MaxLeiter/sortablejs-vue3#42]
Can someone confirm that https://sortablejs-vue3.maxleiter.com/ is working properly on latest versions of chrome/edge on Windows?

In my case, it works *once* if I do some heavy random clicking. There are no usable messages in console.

I did already mention this here: https://github.com/SortableJS/vue.draggable.next/issues/191

**Comment by singerla** [comment]
I could figure out why this was happening: I'm running windows on a virtual machine and mouse capturing was not working properly.

Really strange, because no other windows functionality was affected by this, just drag and drop inside edge & chrome...

**Comment by XiaoBaiClassmate** [comment]
@singerla  Excuse me,Do you occasionally find that click and drag content doesn't work on Google Chrome?But it works in Firefox

**Comment by singerla** [comment]
My issue was related to a wrong setting in VirtualBox related to mouse integration. The symptoms described above were misleading me into a completely wrong direction and not at all unrelated to sortableJs. :smile: 

If you also have to rely on a Win10 Guest in VirtualBox to test Edge, you might want to check your selected pointer device. This fixed the issue for me.
