### ISSUE TITLE
Issue swapping draggable elements

### ISSUE THREAD

**Issue by clementrcheng** [MaxLeiter/sortablejs-vue3#46]
Hello,

I’m hoping to get some help with what I’m trying to implement.

I have two sections of tile slots with tiles inside, and need to be able to drag/move tiles to different tile slots. I’m treating each Sortable component as a tile slot and using the item template to render a draggable tile. Each tile slot can either have no tile or just a single tile. So for my use case, the list prop’s array should never have more than 1 element.

If a tile slot has a tile, it can either be locked or not locked. If it is locked, I’m passing in the SortableJS disable prop as true to the options prop. This works fine because when I drag tile B to a tile slot which has tile A locked, the on move handler is never fired, tile A does not move and tile B is returned to its original tile slot. 

However, if tile A is not locked, I’m hoping to be able to swap the positions of tile A and tile B. I’m having two issues in this case:
1. When dragging tile B over tile A, it looks like tile A gets pushed out of the tile slot. I don’t want this. (refer to screenshot e below)
2. When I let go, there are now 2 B tiles in the tile slot, even though the list prop that’s passed down only contains one tile B. (refer to screenshot f)

**Questions:**
1. Is there a way to prevent this from happening without setting the SortableJS disabled prop in the options prop? I was hoping I could return false in the move event handle to cancel the move (https://github.com/SortableJS/Sortable#options), and in the on end handler, emit an event to the parent component which would update the list prop, but cancelling the move doesn’t seem to work. The issue with setting the disabled prop is that the on end handler’s event.to object is then not correct.
2. There seems to be a conflict with Vue trying to re-render the page and the library also manipulating the DOM at the same time, thus causing there to be two tiles in the single tile slot even though the Sortable list prop only has 1 item.
3. I know SortableJS has a swap plugin, is there a way to enable that in sortablejs-vue3?

Thanks in advance!

**Screenshots:**

a)Initially with empty tile slots:
<img width="259" alt="1-initially empty tile slots" src="https://user-images.githubusercontent.com/6100103/205376750-51a97caa-a72c-4a59-94be-67e8d4f14f86.png">

b)Tile A placed in tile slot position 2, unlocked:
<img width="258" alt="2-tile A unlocked" src="https://user-images.githubusercontent.com/6100103/205376756-fadc2d40-4663-42a2-82e6-5a1e5376a771.png">

c)Tile A locked:
<img width="252" alt="3-tile A locked" src="https://user-images.githubusercontent.com/6100103/205376758-90653e27-4835-4053-8f29-0472f754a175.png">

d)Trying to swap Tile B with Tile A when Tile A is locked, Tile A does not get pushed out (using the disabled prop):
<img width="200" alt="4-trying to swap tiles when locked" src="https://user-images.githubusercontent.com/6100103/205376760-e806dea9-5550-4d03-a345-cbf41570160f.png">

e)Trying to swap Tile B with Tile A when Tile A is not locked, causing Tile A to get pushed out. This is before letting go of the drag:
<img width="218" alt="5-trying to swap tiles when unlocked" src="https://user-images.githubusercontent.com/6100103/205376763-1b985adc-f370-44ee-9d7d-d94158769c6b.png">

f)After letting go of the drag, Tile A is correctly removed but Tile B is now duplicated in the tile slot when it shouldn't be:
<img width="224" alt="6-after swapping" src="https://user-images.githubusercontent.com/6100103/205376765-c7eb6b42-90b6-4616-bb6d-f0b672ecb156.png">

**Comment by MaxLeiter** [comment]
Thanks for the clear issue. I think most of your points are addressed in #44.

As for using swap and other plugins, just pass them into the `options` prop using the SortableJS syntax:
https://sortablejs.github.io/Sortable/#swap

**Comment by headmandev** [comment]
@MaxLeiter Just passing a prop like swap is not enough.
If we mount Swap before importing you package, as the documentation says, it does not work.
```js
import { Sortable as SortableJs, Swap } from 'sortablejs/modular/sortable.core.esm';
Sortable.mount(new Swap());
SortableJs.mount(new Swap());
```


We have to mount it like below

```js
import SortableJs from 'sortablejs';
import { Swap } from 'sortablejs/modular/sortable.core.esm';
SortableJs.mount(new Swap());

import { Sortable } from "sortablejs-vue3";
```

Mentioning that somewhere would be great, I did not immediately understand it. 
Thank you!

**Comment by MaxLeiter** [comment]
I've updated the README. Thanks @headmandev

**Comment by quilkin** [comment]
I have two problems using the method that @headmandev suggested: 
1. "Could not find a declaration file for module 'sortablejs/modular/sortable.core.esm'"
2.   Cannot use 'mount' before 'import' ("An import declaration can only be used at the top level of a module")
Packages:
├── @vitejs/plugin-vue@4.0.0
├── sortablejs-vue3@1.2.8
├── sortablejs@1.15.0
├── vite@4.1.4
├── vue@3.2.47
└── vuetify@3.1.11
(Problem happened before I added Vuetify)
