### ISSUE TITLE
Using options API

### ISSUE THREAD

**Issue by davisums** [MaxLeiter/sortablejs-vue3#6]
Hey there,

I'm trying to use the library as recommended by just adding the main js file my project instead of installing it as a dependency. The rest of my codebase I'm using the options API though and I'm having trouble getting this to work with the options API. (Works fine using composition API). 

What's giving me trouble specifically is the watcher. I've tried two different ways (and many more actually) but none of these seem to work. The watcher is never triggered:

```
<script>
export default {
  data(){
    return {
    }
  },
  props: ['options', 'list', 'itemKey', 'tag'],
  emits: ['choose', 'unchoose', 'start', 'end', 'add', 'update', 'sort', 'remove', 'filter', 'move', 'clone', 'change'],
  mounted(){
    this.$watch(
      () => {
          return this.$refs.containerRef
      },
      (val) => {
        console.log(val)
        alert('App $watch $refs.containerRef: ' + val)
      }
    )
  },
  unmounted(){
    if (this.$refs.sortable) {
      this.$refs.containerRef = null;
      this.$refs.sortable = null;
    }
  },
  watch: {
    containerRef(newDraggable, oldDraggable){
      if (newDraggable) {
        this.$refs.sortable = new Sortable(newDraggable, {
          ...props.options,
          group: "shared",
          onChoose: (event) => this.$emit("choose", event),
          onUnchoose: (event) => this.$emit("unchoose", event),
          onStart: (event) => this.$emit("start", event),
          onEnd: (event) => this.$emit("end", event),
          onAdd: (event) => this.$emit("add", event),
          onUpdate: (event) => this.$emit("update", event),
          onSort: (event) => this.$emit("sort", event),
          onRemove: (event) => this.$emit("remove", event),
          onFilter: (event) => this.$emit("filter", event),
          onMove: (event, originalEvent) => this.$emit("move", event, originalEvent),
          onClone: (event) => this.$emit("clone", event),
          onChange: (event) => this.$emit("change", event),
        });
      }
    }
  }
}
</script>
```

Any thoughts on how to implement the watcher using options?

And thanks for the great work, this has been super useful!

**Comment by MaxLeiter** [comment]
Hmmm -- well, this isn't a fix but is there a reason you need to use the options API? I personally much prefer the composition API after using it, and at least this component seems fairly easy to convert over. 

In terms of the problem, I'm not sure why it's occurring, but I *think* it's due to trying to watch `containerRef`. At least with the composition API you're supposed to watch for a data item belonging to the ref. https://stackoverflow.com/questions/39035498/vuejs-watch-refs has some more info.

Is `containerRef(newDraggable, oldDraggable)` never firing at all?

**Comment by MaxLeiter** [comment]
Closing without more information
