### ISSUE TITLE
Can't import in Vue script

### ISSUE THREAD

**Issue by leogenot** [MaxLeiter/sortablejs-vue3#60]
I can't `import { Sortable } from "sortablejs-vue3";` in my Composition api script : 

`GET http://localhost:5173/node_modules/.vite/deps/sortablejs-vue3.js?t=1673724793576&v=19972475 504 (Gateway Timeout)`

tried putting my script in Ts did not help either, the import statement alone makes my app crash...

**Comment by MaxLeiter** [comment]
This seems like a vite problem. Can you report it there?

**Comment by leogenot** [comment]
yes no problem!
