### ISSUE TITLE
Header and footer without the tags?

### ISSUE THREAD

**Issue by jwmoreland** [MaxLeiter/sortablejs-vue3#62]
I like that you can add a header and footer, however I  would like it without the <header> and <footer> tag. In our case we have an upload button at the end, but since the layout is in a css grid, the footer tag messes with the layout. Would it be possible to just have the slot and no html, and the app could inject the footer tag if necessary? Otherwise, if that's a breaking change, maybe add a slot for 'prepend' and 'append'?

**Comment by MaxLeiter** [comment]
A pull request removing the <footer> and <header> would be accepted 👍

**Comment by jwmoreland** [comment]
Thanks. I submitted a pull request.
