### ISSUE TITLE
Make SortableJS-vue3 compatible with vue2 ?

### ISSUE THREAD

**Issue by messenjer** [MaxLeiter/sortablejs-vue3#69]
I know it sounds like a weird proposal.

At the end of the year, vue2 will reach [end of life](https://v2.vuejs.org/lts/) and that will imply that a lot of big legacy projects will have to migrate to vue3. 

The migration is not so trivial, you have to migrate: 
* vue2 to vue3
* core libraries: `vue-router`, `vuex`, .. 
* big ui libraries like `vuetify`, `vue-bootstrap`, ...
* libraries like `Vue.Draggable` where there is no vue3 compatible version released as explained in the `SortableJS-vue3` description

One approach is to be prepared to already migrate the legacy code base of the applications to vue2/vue3 compatible plugins, libraries
* There are small libraries that work in vue2 or vue3 because the code is very basic like https://github.com/myst729/vue-json-tree 
* Or an alternative is to use [vue-demi](https://github.com/vueuse/vue-demi) to write Universal Vue Libraries for Vue 2 & 3 

If `SortableJS-vue3` becomes compatible with Vue2 using `vue-demi`, we could start migrating `Vue.Draggable` in vue2 legacy code to `SortableJS-vue3` and then make it easier to migrate to vue3. 

What do you think?

Mathieu

**Comment by MaxLeiter** [comment]
Thanks for the comprehensive write-up! I wasn't familiar with vue-demi. My one fear is this increases the bundle size, so I'll need to verify that, but otherwise the PR seems good to go.

**Comment by messenjer** [comment]
Thanks. Yes, it's also the first time I've taken a closer look at [vue-demi](https://github.com/vueuse/vue-demi). It's like your project: simple, small, and does exactly what it's supposed to do.

I made the adaptations you asked for in the PR https://github.com/MaxLeiter/sortablejs-vue3/pull/70

**Comment by MaxLeiter** [comment]
Closed by #70 

Thanks a lot @messenjer!

**Comment by messenjer** [comment]
Hello @MaxLeiter , 

I tried to make the plugin work with a vue2 test application, and I can't. I suggest that we revert to my PR https://github.com/MaxLeiter/sortablejs-vue3/pull/70 , and I will do a repro at vue-demi to try to find a solution. 

I'm sorry...

Regards

Mathieu
