### ISSUE TITLE
Works like crap

### ISSUE THREAD

**Issue by cpgb85** [MaxLeiter/sortablejs-vue3#74]
I feel the point of a draggable library in vue is it should automatically change the order in the vue object.  It does not do that, you might as well use jquery ui sort.

**Comment by MaxLeiter** [comment]
Check the README for updating your store. You’re welcome to use jQuery.

**Comment by cpgb85** [comment]
Still doesn't work. it should be updating the array on the fly. it doesn't work as intended.

**Comment by MaxLeiter** [comment]
I won't be helping you due to your title and attitude. Best of luck.

**Comment by cpgb85** [comment]
> I won't be helping you due to your title and attitude. Best of luck.

I apologize for my bad attitude and behavior.  I don't know if this is possible but can you please delete this thread if possible?
