### ISSUE TITLE
e.preventDefault() not working?

### ISSUE THREAD

**Issue by quilkin** [MaxLeiter/sortablejs-vue3#81]
I am trying to stop a drag from list A to list B (drags from B to A are allowed). I have tried handling both the `move` and the `end` events, but cannot prevent them:
`  function checkMove(e) {
    var c = e.cancelable;
    if (e.to.dataset.list == "startGrid")
        e.preventDefault();
  }`
the debugger clearly shows 'preventDefault' being reached, but the move still ocurs. This seems pretty basic; what am I doing wrong here?

**Comment by MaxLeiter** [comment]
Sorry this isn't documented well, but as of https://github.com/MaxLeiter/sortablejs-vue3/pull/56 you can pass an `attrs` object to the library with a `onMoveCapture` function to return false/true/etc based on your logic.
